### ISSUE TITLE
Missing requirements.txt in the daam pypi package

### ISSUE THREAD

**Issue by federicotorrielli** [castorini/daam#11]
![image](https://user-images.githubusercontent.com/31370059/204759914-765098b9-b1dc-495b-a834-1d16a7304f25.png)
![image](https://user-images.githubusercontent.com/31370059/204760104-e9463870-d55d-4a2e-a542-4c79279d167d.png)

@daemon

**Comment by federicotorrielli** [comment]
(Thanks for the great and fast work, by the way!)

**Comment by daemon** [comment]
Oops, thanks for pointing this out. The latest release (0.0.8) should cover that.
