### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by federicotorrielli** [castorini/daam#12]
![image](https://user-images.githubusercontent.com/31370059/204836649-7de4167d-04a6-4e41-b950-c55dd0daaa3a.png)

When calling `heat_map_lemma = tc.compute_global_heat_map(prompt)`

**Comment by daemon** [comment]
Odd, can you share the prompt and surrounding code?

**Comment by federicotorrielli** [comment]
Sure, this is the pipe 
![image](https://user-images.githubusercontent.com/31370059/204864469-0bb6e248-bca1-4182-a98a-183c99c03a10.png)
And this is the call
![image](https://user-images.githubusercontent.com/31370059/204864573-eafe02fe-532e-44ba-80a9-0d73a5ce23dc.png)

lemmas is just a list of string prompts. For the generator I used:
```python
def initialize_generator(self):
    gen = torch.Generator(device='cuda')
    seed = 26111998
    return gen.manual_seed(seed)
```

**Comment by daemon** [comment]
Ah, I think I see the problem. DAAM doesn't support sliced attention. I'll release an update for that.

**Comment by daemon** [comment]
Fixed in latest release.
