### ISSUE TITLE
ImportError: cannot import name 'plot_overlay_heat_map', 'expand_image' from 'daam'

### ISSUE THREAD

**Issue by jena-shreyas** [castorini/daam#23]
I installed daam in Google Colab with the following environment specs:-

Ubuntu 18.04
Python 3.8
Pytorch 1.13
CUDA 11.6

![Screenshot from 2022-12-10 11-25-14](https://user-images.githubusercontent.com/85274016/206835192-7e0587d5-42d8-4a76-b292-edfbbb0ff6bb.png)

I encountered the following error when I tried to import 'plot_overlay_heat_map' and 'expand_image' from daam ('trace' and 'set_seed' were imported without any fuss though):

![Screenshot from 2022-12-10 11-35-53](https://user-images.githubusercontent.com/85274016/206835244-7ea9fd82-54fe-469d-91c9-6692b23c33e4.png)

**Comment by daemon** [comment]
Ah yeah that colab was for an older version of DAAM. I’ll make another one soon!

**Comment by daemon** [comment]
Added Colab notebook for v0.0.11: https://colab.research.google.com/drive/1miGauqa07uHnDoe81NmbmtTtnupmlipv?usp=sharing
