### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList #12

### ISSUE THREAD

**Issue by UdonDa** [castorini/daam#25]
Hi, @daemon 

I encounter the same error as #12 .
My program is the same as the example code in https://github.com/castorini/daam#:~:text=as%20a%20Library-,Import,-and%20use%20DAAM .

I was debugging daam, but I do not know the reason.
Do you know the reason?

<img width="619" alt="Screenshot 2022-12-24 18 26 10" src="https://user-images.githubusercontent.com/25411643/209429656-c63e4d69-a03e-4874-997d-39c6c6ca388e.png">

**Comment by daemon** [comment]
Curious, I'm looking into it. I wasn't able to reproduce the error on my end -- I'll try with a fresh install soon. Here's my environment:
https://gist.github.com/daemon/4ffc94ab4454777cfedeb95d1b7c7d42

**Comment by daemon** [comment]
Did a fresh install on an AWS G5 instance with an Ubuntu Deep Learning AMI, wasn't able to reproduce either:
https://gist.github.com/daemon/ba5d62ff65b19be5686e9c0081bf2748

It's possible the installed hook (see `trace.py`) has been overridden by something that's not part of DAAM. Are there any other packages that would have the same effect? Is a package forcing a different kind of attention to be used?

**Comment by daemon** [comment]
Please re-open if this is still a problem.
