### ISSUE TITLE
about negative prompt

### ISSUE THREAD

**Issue by spikezz** [castorini/daam#33]
Does this approch work for negative prompt?

**Comment by daemon** [comment]
I haven't tried this, but it would be nice to have.

**Comment by spikezz** [comment]
I have checked the way negative prompt works:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Negative-prompt
it looks like does not make sense to directly map Negative-prompt to pixels with positive prompt together, but still I try to put only the negative prompt in the positive basket and draw it out to see how they affect the pixels(in the bad picture) to understand how the Negative-prompt works, so it is still useful form some perspective.

Nice Work anyway!
