### ISSUE TITLE
about image size and prompt length

### ISSUE THREAD

**Issue by mylee95** [castorini/daam#43]
Hi, firstly thank you for sharing your great work. 

While reading your paper and code, I had question about image size and prompt length. 
It seems like your code only accepts image size of 512x512 or 768x768, and with maximum prompt length of 75+2, which is limit of text encoder. 
However, if my understanding is correct, there is no problem with getting attribution maps while making any size of image with longer prompt. 

Is it correct? Or is there any other reason that daam is coded with such a limitation?

**Comment by daemon** [comment]
In theory, there's no limit to context length or image size. My understanding is that the models themselves have those aforementioned constraints.

**Comment by mylee95** [comment]
@daemon thank you for quick reply! I'll try changing code to make sure any image size or context length can be accepted.
