### ISSUE TITLE
Report a mistake(maybe)

### ISSUE THREAD

**Issue by SDaoer** [castorini/daam#44]
Thanks for your code. I am following your work, and I found a piece of confusing code that might be a mistake. It is in the file `hook.py` lines 103 and 104:
`up_names = ['up'] * len(model.up_blocks)`
`down_names = ['down'] * len(model.up_blocks)`
Shouldn't it probably be:
`down_names = ['down'] * len(model.down_blocks)`

**Comment by daemon** [comment]
Ah yeah, that's more robust for models without the same number of upsampling and downsampling blocks. I'll fix that soon.
