### ISSUE TITLE
Collab Demo

### ISSUE THREAD

**Issue by anas-zafar** [castorini/daam#46]
Thank you for the amazing work. I am trying to run the Collab demo. I am getting the error below while loading the model:

```
model = StableDiffusionPipeline.from_pretrained('stabilityai/stable-diffusion-2-base')
AttributeError: module transformers has no attribute CLIPImageProcessor
```

**Comment by daemon** [comment]
It looks like the package requirements for `daam==0.0.11` missed version numbers, eventually causing this issue. It shouldn't be a problem with the latest version of DAAM (`0.1.0`), and I can confirm that changing the initial `!pip install daam==0.0.11` to `!pip install daam==0.1.0` fixes this bug.

Thanks for raising this. I'll update the official Colab notebook.
