### ISSUE TITLE
Write tutorials in a notebooks folder

### ISSUE THREAD

**Issue by daemon** [castorini/daam#7]
It would be nice to have tutorials and a Colab playbook.

**Comment by amrrs** [comment]
@daemon I've managed to create a tutorial for this - https://www.youtube.com/watch?v=J2WtkA1Xfew Thanks for the great work Team!

**Comment by daemon** [comment]
Thanks! This is great. I actually found your video through Twitter before I saw this comment. I added it to the readme.
