### ISSUE TITLE
Add Stable Diffusion V2 support

### ISSUE THREAD

**Issue by daemon** [castorini/daam#9]
Add Stable Diffusion V2 support.

**Comment by federicotorrielli** [comment]
This is awesome, really looking forward!

EDIT: between tomorrow and the day after the diffusion team is going to update the diffusers package, I reckon you should wait until 0.9.0

**Comment by daemon** [comment]
Cool, that sounds about right.

**Comment by federicotorrielli** [comment]
Diffusers 0.9.0 is out

**Comment by daemon** [comment]
Yep! I'm currently swamped with extending the paper, but I'll get around to it. If you (or anyone) wants to submit a PR for it, I'd also be happy to review.

EDIT: Actually, I'll spend a bit of time tonight to see if I can do it quickly.

**Comment by federicotorrielli** [comment]
I can take a look at the code for sure, but I'll bet that you and the other authors could do a better job at it than me

**Comment by daemon** [comment]
Updated to support V2. Check out the readme for the CLI utility as well.
